# -*- coding: utf-8 -*-
"""16 pipes Despliegue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gz9qWGLPkDxEDVUtMIkRI_2G4lEBtflU

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Aplicar tubería
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Paso 1: Limpiar atípicos
def remove_outliers(X):
    #Se asigna valor nulo a los atípicos
    X.loc[(X["Edad"] < 12) | (X["Edad"] > 50), "Edad"] = np.nan
    X.loc[(X["Sexo"] != "Mujer") & (X["Sexo"] != "Hombre"), "Sexo"] = np.nan
    return X

#Cargamos el pipeline con el modelo
import pickle
filename = 'pipeline_modelo.pkl'
pipeline = pickle.load(open(filename, 'rb'))
pipeline

#Cargamos los datos futuros
data = pd.read_csv("videojuegos-datosFuturos.csv")
data.head()

#Hacemos la predicción con el Tree
Y_Tree = pipeline.predict(data)
print(Y_Tree)

data['Prediccion']=Y_Tree
data